### PR TITLE
Updated for Pascal_Voc Dataloader

### PR DESCRIPTION
**Pull request by ZongxianLee**
A pascal_voc liked dataloader is implemented in this update which makes the project can also be trained by feeding the pascal_voc form datasets.

### CODE REVIEW

**Comment by Hello526** [comment]
您好，请问您是否在PASCAL VOC2012上训练过YOLOV3，不知道它的mAP能达到多少？我查找了很多文献，都没有找到相关的内容。

**Comment by libzzluo** [comment]
@Hello526 是的，原论文只有COCO的训练测试结果，我也在找....

**Comment by eriklindernoren** [comment]
@ZongxianLee Thanks for the PR. I'll try this out as soon as I have time. :)

**Comment by EverWinter23** [comment]
`File "/content/clover/utils/datasets.py", line 246, in __getitem__
    x1 = target[:,1]
IndexError: too many indices for array`

Error when I use the build from 11 Jul 2018 for this patch. Other wise we don't have callote_fn for current build.

**Comment by tc-qaq** [comment]
@Hello526
map@50能到 80 但我只能训练到72

**Comment by www12345678** [comment]
@tc-qaq 
你训练时epochs选的多大呀？

**Comment by tc-qaq** [comment]
@www12345678  100

**Comment by Flova** [comment]
The data loader has been reworked. This PR would need some work to get it up to date. @ZongxianLee are you interested in updating this PR?

**Comment by Flova** [comment]
I close this for now. If you are still interested, you can ping me and I reopen it.

**Pull request closed without merging**
