### PR TITLE
Add CI

### PR DESCRIPTION
**Pull request by Borda**
some code cleaning and adding Travis...

### CODE REVIEW

**Comment by Borda** [comment]
@eriklindernoren could you have look... ^^

**Comment by Borda** [comment]
@eriklindernoren could you have look... ^^

**Comment by Flova** [comment]
I thought about adding a CI! Thanks for showing me this PR.
The project would definitely benefit.

I mainly worked with GitHub actions in the past. They are free for open-source projects and quite easy to use/maintain. 
Is there also such a free plan for Travis? Is there any way to test GPU stuff with Travis? Afaik GitHub actions do not feature GPUS

**Comment by Borda** [comment]
well as you can see I have done this more than a year ago when there were no GH actions yet :D
so far I know the only CI offering GPUs is CircleCI but it is not free even for open-source :/

**Comment by Flova** [comment]
I know. This wasn't meant offensive in any way ^^
What's your opinion? Do we want to try GitHub Actions?

And what should we add to the CI? Definitely some linting stuff, but for tests maybe some small training and eval on dummy data (only one Epoch just to see if it crashes on some sample images)

**Comment by Borda** [comment]
yes, GH actions are good, but I do not have time to write, so if you are interested you cat take this one as a starting point and anytime later replace it with something better :]
the actual PR does some small fixes/refactoring and executes Tox which contains `pytest` and `flake8`

**Comment by Borda** [comment]
@Flova so how about this PR, shall I resolve conflicts to get it merged or close it? 🐰

**Comment by Flova** [comment]
This PR is still cool and relevant, but I am currently working on #504 and #616. Therefore the CI is currently a lower priority. But If you want to work on it feel free, I would review and test it.

**Comment by Borda** [comment]
It seems that Travis lower free open-source builds d=so this does not make sense anymore...

**Comment by Flova** [comment]
Oh. Nevertheless thanks for your contribution.

**Pull request closed without merging**
